@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor user
user -> Interfaz: Consultar disponibilidad del recurso
Interfaz --> Servidor: Envíar solicitud
database Mongo
Servidor  --> Mongo: Obtiener la respuesta
Servidor  --> Interfaz: Devuelver la respuesta
Interfaz --> user: Mostrar la respuesta
@enduml